"""добавлена таблица group и поле group_id

Revision ID: 7b287e9af231
Revises: b529f9fde7a2
Create Date: 2026-07-25 21:03:31.330008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b287e9af231'
down_revision = 'b529f9fde7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_contact_group_id_group'), 'group', ['group_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contact_group_id_group'), type_='foreignkey')
        batch_op.drop_column('group_id')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
